### ISSUE TITLE
Store previously generated feeds also in feed.json 

### ISSUE THREAD

**Issue by athityakumar** [metakgp/naarad-source#12]
Currently, the `feed.json` is created / over-written on a one-time basis on running `fbscraper.py`. However, wouldn't it better if we keep adding the new feed into the `feed.json` without overwriting the existing stuff?

Also, maybe we can keep an `archive` condition as a field in `feed.json` like

if today - post_date > 3 months => archive = True
else archive = False

In this way, we can store lots of data, spanning over a big time-period!

**Comment by athityakumar** [comment]
@DefCon-007 : Can you take care of this issue? We want the `feed.json` file to be appended by the new feed, rather than get overwritten.

**Comment by DefCon-007** [comment]
@athityakumar This has already been fixed by @hargup  in #123db7d017c3c981763d709fcc89264e8744cb54039

**Comment by athityakumar** [comment]
@DefCon-007 : Oh, just noticed it. Thanks! Also, the `feed.json` still contained duplicates on running the `fbscraper.py`- so I had changed the `remove_duplicates` function. So can you 

(1) pull the present code 
(2) delete the existing `feed.json` / remove the existing duplicates,
(3) run the big terminal script I told you yesterday / `deploy.sh` and push the good `feed.json` file

**Comment by vivekiitkgp** [comment]
I think this has been fixed.
