### ISSUE TITLE
The image of a event is too small 

### ISSUE THREAD

**Issue by DefCon-007** [metakgp/naarad-source#23]
I think it downloads the thumbnail only. 
<img width="1102" alt="screen shot 2016-08-20 at 6 55 48 pm" src="https://cloud.githubusercontent.com/assets/16754547/17831493/df9b6bd6-6707-11e6-8028-931cfe25bb5a.png">

**Comment by athityakumar** [comment]
@DefCon-007 : Even if it's a thumbnail, shouldn't changing the `width` and `height` parameters in the `<img>` tag of `feed.tmpl` do the trick?

**Comment by DefCon-007** [comment]
@athityakumar  Image is too short. Doing so will pixelated it badly.
![image](https://cloud.githubusercontent.com/assets/16754547/17833391/416c54de-6739-11e6-9692-35020f5a17bd.png)

**Comment by athityakumar** [comment]
@DefCon-007 : Alright, then we'd have to check the facepy API if they offer a separate field for images of events

**Comment by DefCon-007** [comment]
@athityakumar @hargup : This issue should also be fixed before the release.I have two tests on 31st morning so I will try to resolve this and other issues on 31st evening.
