### ISSUE TITLE
Include naarad into meta-x / heroku for automatic cron job

### ISSUE THREAD

**Issue by athityakumar** [metakgp/naarad-source#26]
Just an enhancement that can even be done later. A cron job that just runs the deploy.sh file once everyday so that the `feed.json` file is always updated.

**Comment by hargup** [comment]
We also run it from the metakgp server, @athityakumar please you send me your ssh pub key so that I can give you access to the metakgp account.

**Comment by athityakumar** [comment]
@hargup : Almost forgot about giving you my ssh pub key... Sorry! 

I've sent you the key in slack. :smile:
