### ISSUE TITLE
Search is not working for simple queries

### ISSUE THREAD

**Issue by hargup** [metakgp/naarad-source#27]
Few example
- The post regarding WTMS is the first post in the list but searching for "WTMS" or "music" doesn't show up the post even if these terms are there in the post.
- Searching for "Kshtij" instead of "Kshitij" doesn't show up the post about Hack Camp by Kshitij

**Comment by athityakumar** [comment]
Yep, maybe we should change the fuzzy search into a rather simple strict-matching search.

Because, we didn't have a lot of text in mfqp / mcmp , but here each post has lots of text - enough to confuse a fuzzy search.

**Comment by athityakumar** [comment]
Ping @hargup @DefCon-007 - This is one major issue to be resolved, before release.

**Comment by iamharshit** [comment]
@hargup if you could pinpoint me to the file where code for `Search` is written ,it would be helpful

**Comment by athityakumar** [comment]
@iamharshit - Search files have been removed from this repo, but can be found in the deployed metakgp/naarad repository here (https://github.com/metakgp/naarad/tree/master/docs/js) - custom.js, worker.js, worker2.js, fuse.min.js files.

**Comment by athityakumar** [comment]
[Discussion] 

Can we use datatable library (https://datatables.net/examples/api/regex.html) to take care of both search & pagination?

Ping @hargup @icyflame @DefCon-007 @vivekiitkgp

**Comment by icyflame** [comment]
@athityakumar I have used DataTables, and it is a very good library. Although, I am not sure how you plan to use it here. Remember that using Tables for UI is not good practice and out of the question. I think we probably need to look into exactly what is being "Fuzzy searched", and then decide on whether we really need to move away from it. Fuse is a good library.

**Comment by DefCon-007** [comment]
Can we add priorities in fuzzy search ? Like first it will look for page name and so on ..

**Comment by athityakumar** [comment]
Accomplished with PR #80 :tada:
