### ISSUE TITLE
Replace front-end

### ISSUE THREAD

**Issue by athityakumar** [metakgp/naarad-source#44]
The existing template doesn't seem good on large devices & is weirdly also not mobile responsive (though it is supposed to be). So, replace this by any light-weight theme preferable from bootstrap.

**Comment by iamharshit** [comment]
Can you tell what features you need in new template ?

**Comment by iamharshit** [comment]
@athityakumar does the front-end still need to be replaced? 
If yes then can you suggest a light weight theme you desire.

**Comment by athityakumar** [comment]
@DefCon-007 @vivekiitkgp @icyflame - I think this has been fixed with PR #48. Can we close this issue now?

**Comment by DefCon-007** [comment]
Sure

**Comment by icyflame** [comment]
yes
