### ISSUE TITLE
Add a last updated timestamp

### ISSUE THREAD

**Issue by DefCon-007** [metakgp/naarad-source#52]

**Comment by iamharshit** [comment]
should  we just need to store the last updated time stamp in a `.txt` file or we need it display it somewhere also

**Comment by DefCon-007** [comment]
Add it to the website's footer

**Comment by americast** [comment]
I have tried to resolve the issue and also created a pull request.

**Comment by americast** [comment]
Screenshot:
![2016-12-13-180922_1366x768_scrot](https://cloud.githubusercontent.com/assets/23132358/21140674/6807729c-c15f-11e6-97a7-8e09d4236690.png)
The last updated time is shown at the top right corner.

**Comment by athityakumar** [comment]
Taken care of, with PR #62 . Closing this issue.
