### ISSUE TITLE
Change font to Linux Libertine

### ISSUE THREAD

**Issue by icyflame** [metakgp/naarad-source#56]
Suggested by @vivekiitkgp.

@athityakumar please create a PR for this, we will get a few opinions after, I am sure. :slightly_smiling_face:

**Comment by iamharshit** [comment]
@icyflame @athityakumar @DefCon-007 can you pinpoint the file which needs to be manipulated for changing font to Linux Libertine

**Comment by DefCon-007** [comment]
It has been done.
