### ISSUE TITLE
Save images from different pages to different directories inside output

### ISSUE THREAD

**Issue by DefCon-007** [metakgp/naarad-source#7]

**Comment by vivekiitkgp** [comment]
@DefCon-007 Additionally, compress images to reduce size.

**Comment by DefCon-007** [comment]
@vivekiitkgp : Naarad previously downloaded the images. It was removed afterwards. Why should we save the images ?

**Comment by vivekiitkgp** [comment]
Oh. Does it directly link to the image sources now?
