### ISSUE TITLE
Show last updated time

### ISSUE THREAD

**Issue by hargup** [metakgp/naarad-source#70]
The page should show the last updated time somewhere, so that it is easy to know if naarad is working.

**Comment by hargup** [comment]
@americast will you interested in fixing this?

**Comment by americast** [comment]
Dear @hargup, I had already worked on this during KWoC 2016. See pull #62 (https://github.com/metakgp/naarad-source/pull/62)

**Comment by hargup** [comment]
Pretty cool, didn't notice it earlier.
